version: "3.8"

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_backend_container
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  admin-backend:
    build: ./admin-backend
    container_name: my_admin_backend
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - db

volumes:
  postgres_data:
