-- Rollback for migration 002
ALTER TABLE categories DROP COLUMN IF EXISTS slug;
ALTER TABLE categories DROP COLUMN IF EXISTS seo_title;
ALTER TABLE categories DROP COLUMN IF EXISTS seo_description;

ALTER TABLE models DROP COLUMN IF EXISTS slug;
ALTER TABLE models DROP COLUMN IF EXISTS seo_title;
ALTER TABLE models DROP COLUMN IF EXISTS seo_description;
ALTER TABLE models DROP COLUMN IF EXISTS h1;
ALTER TABLE models DROP COLUMN IF EXISTS content;
ALTER TABLE models DROP COLUMN IF EXISTS is_indexable;

ALTER TABLE parts DROP COLUMN IF EXISTS slug;
ALTER TABLE slides DROP COLUMN IF EXISTS has_svg;
ALTER TABLE orders DROP COLUMN IF EXISTS updated_at;
